// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_feed_follow.sql

package database

import (
	"context"
	"database/sql"
)

const delete_Feed_Follow = `-- name: Delete_Feed_Follow :exec

DELETE FROM feed_follows a
WHERE a.user_id = $1 and a.feed_id = $2
`

type Delete_Feed_FollowParams struct {
	UserID sql.NullInt32
	FeedID sql.NullInt32
}

func (q *Queries) Delete_Feed_Follow(ctx context.Context, arg Delete_Feed_FollowParams) error {
	_, err := q.db.ExecContext(ctx, delete_Feed_Follow, arg.UserID, arg.FeedID)
	return err
}
