// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_feed_by_url.sql

package database

import (
	"context"
)

const getFeed_ByURL = `-- name: GetFeed_ByURL :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at
FROM feeds 
WHERE url = $1
`

func (q *Queries) GetFeed_ByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed_ByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
