// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: GetNextFeedToFetc.sql

package database

import (
	"context"
)

const get_Next_Feed_to_fetch = `-- name: Get_Next_Feed_to_fetch :one

SELECT id, created_at, updated_at, name, url, user_id, last_fetched_at
FROM feeds 
ORDER BY last_fetched_at NULLS FIRST
LIMIT 1
`

func (q *Queries) Get_Next_Feed_to_fetch(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, get_Next_Feed_to_fetch)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetchedAt,
	)
	return i, err
}
