// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: MarkFeedFetched.sql

package database

import (
	"context"
)

const mark_Feed_Fetched = `-- name: Mark_Feed_Fetched :exec

UPDATE feeds
SET updated_at = NOW(), 
    last_fetched_at = NOW()
WHERE id = $1
`

func (q *Queries) Mark_Feed_Fetched(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, mark_Feed_Fetched, id)
	return err
}
